# Set up a development environment using the conda package manager
name: dependente
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - make
  # Run-time
  - click>=8.0.0,<9.0.0
  - rich>=9.6.0,<11.0.0
  - tomli>=1.0.0,<3.0.0
  # Building (excluding setuptools)
  - build
  # Testing
  - pytest
  - pytest-cov
  - coverage
  # Linting and style
  - black
  - isort
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - pep8-naming
  - pip:
    - flake8-unused-arguments
